package org.yogurt.testClasses;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

public final class PersonProtos {
  private PersonProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PersonOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    // required string name = 2;
    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional string email = 3;
    /**
     * <code>optional string email = 3;</code>
     */
    boolean hasEmail();
    /**
     * <code>optional string email = 3;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    // optional int32 money = 4;
    /**
     * <code>optional int32 money = 4;</code>
     */
    boolean hasMoney();
    /**
     * <code>optional int32 money = 4;</code>
     */
    int getMoney();

    // optional .Hair hair = 5;
    /**
     * <code>optional .Hair hair = 5;</code>
     */
    boolean hasHair();
    /**
     * <code>optional .Hair hair = 5;</code>
     */
    PersonProtos.Hair getHair();
    /**
     * <code>optional .Hair hair = 5;</code>
     */
    PersonProtos.HairOrBuilder getHairOrBuilder();

    // optional bytes someBytes = 6;
    /**
     * <code>optional bytes someBytes = 6;</code>
     */
    boolean hasSomeBytes();
    /**
     * <code>optional bytes someBytes = 6;</code>
     */
    com.google.protobuf.ByteString getSomeBytes();

    // repeated string language = 7;
    /**
     * <code>repeated string language = 7;</code>
     */
    java.util.List<java.lang.String>
    getLanguageList();
    /**
     * <code>repeated string language = 7;</code>
     */
    int getLanguageCount();
    /**
     * <code>repeated string language = 7;</code>
     */
    java.lang.String getLanguage(int index);
    /**
     * <code>repeated string language = 7;</code>
     */
    com.google.protobuf.ByteString
        getLanguageBytes(int index);

    // repeated int32 someNumber = 8;
    /**
     * <code>repeated int32 someNumber = 8;</code>
     */
    java.util.List<java.lang.Integer> getSomeNumberList();
    /**
     * <code>repeated int32 someNumber = 8;</code>
     */
    int getSomeNumberCount();
    /**
     * <code>repeated int32 someNumber = 8;</code>
     */
    int getSomeNumber(int index);

    // repeated .Car car = 9;
    /**
     * <code>repeated .Car car = 9;</code>
     */
    java.util.List<PersonProtos.Car> 
        getCarList();
    /**
     * <code>repeated .Car car = 9;</code>
     */
    PersonProtos.Car getCar(int index);
    /**
     * <code>repeated .Car car = 9;</code>
     */
    int getCarCount();
    /**
     * <code>repeated .Car car = 9;</code>
     */
    java.util.List<? extends PersonProtos.CarOrBuilder> 
        getCarOrBuilderList();
    /**
     * <code>repeated .Car car = 9;</code>
     */
    PersonProtos.CarOrBuilder getCarOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessage
      implements PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Person(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Person defaultInstance;
    public static Person getDefaultInstance() {
      return defaultInstance;
    }

    public Person getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              email_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              money_ = input.readInt32();
              break;
            }
            case 42: {
              PersonProtos.Hair.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = hair_.toBuilder();
              }
              hair_ = input.readMessage(PersonProtos.Hair.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(hair_);
                hair_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              someBytes_ = input.readBytes();
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                language_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000040;
              }
              language_.add(input.readBytes());
              break;
            }
            case 64: {
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                someNumber_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000080;
              }
              someNumber_.add(input.readInt32());
              break;
            }
            case 66: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080) && input.getBytesUntilLimit() > 0) {
                someNumber_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000080;
              }
              while (input.getBytesUntilLimit() > 0) {
                someNumber_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 74: {
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
                car_ = new java.util.ArrayList<PersonProtos.Car>();
                mutable_bitField0_ |= 0x00000100;
              }
              car_.add(input.readMessage(PersonProtos.Car.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          language_ = new com.google.protobuf.UnmodifiableLazyStringList(language_);
        }
        if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
          someNumber_ = java.util.Collections.unmodifiableList(someNumber_);
        }
        if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
          car_ = java.util.Collections.unmodifiableList(car_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PersonProtos.internal_static_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PersonProtos.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PersonProtos.Person.class, PersonProtos.Person.Builder.class);
    }

    public static com.google.protobuf.Parser<Person> PARSER =
        new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string email = 3;
    public static final int EMAIL_FIELD_NUMBER = 3;
    private java.lang.Object email_;
    /**
     * <code>optional string email = 3;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 money = 4;
    public static final int MONEY_FIELD_NUMBER = 4;
    private int money_;
    /**
     * <code>optional int32 money = 4;</code>
     */
    public boolean hasMoney() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 money = 4;</code>
     */
    public int getMoney() {
      return money_;
    }

    // optional .Hair hair = 5;
    public static final int HAIR_FIELD_NUMBER = 5;
    private PersonProtos.Hair hair_;
    /**
     * <code>optional .Hair hair = 5;</code>
     */
    public boolean hasHair() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .Hair hair = 5;</code>
     */
    public PersonProtos.Hair getHair() {
      return hair_;
    }
    /**
     * <code>optional .Hair hair = 5;</code>
     */
    public PersonProtos.HairOrBuilder getHairOrBuilder() {
      return hair_;
    }

    // optional bytes someBytes = 6;
    public static final int SOMEBYTES_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString someBytes_;
    /**
     * <code>optional bytes someBytes = 6;</code>
     */
    public boolean hasSomeBytes() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bytes someBytes = 6;</code>
     */
    public com.google.protobuf.ByteString getSomeBytes() {
      return someBytes_;
    }

    // repeated string language = 7;
    public static final int LANGUAGE_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList language_;
    /**
     * <code>repeated string language = 7;</code>
     */
    public java.util.List<java.lang.String>
        getLanguageList() {
      return language_;
    }
    /**
     * <code>repeated string language = 7;</code>
     */
    public int getLanguageCount() {
      return language_.size();
    }
    /**
     * <code>repeated string language = 7;</code>
     */
    public java.lang.String getLanguage(int index) {
      return language_.get(index);
    }
    /**
     * <code>repeated string language = 7;</code>
     */
    public com.google.protobuf.ByteString
        getLanguageBytes(int index) {
      return language_.getByteString(index);
    }

    // repeated int32 someNumber = 8;
    public static final int SOMENUMBER_FIELD_NUMBER = 8;
    private java.util.List<java.lang.Integer> someNumber_;
    /**
     * <code>repeated int32 someNumber = 8;</code>
     */
    public java.util.List<java.lang.Integer>
        getSomeNumberList() {
      return someNumber_;
    }
    /**
     * <code>repeated int32 someNumber = 8;</code>
     */
    public int getSomeNumberCount() {
      return someNumber_.size();
    }
    /**
     * <code>repeated int32 someNumber = 8;</code>
     */
    public int getSomeNumber(int index) {
      return someNumber_.get(index);
    }

    // repeated .Car car = 9;
    public static final int CAR_FIELD_NUMBER = 9;
    private java.util.List<PersonProtos.Car> car_;
    /**
     * <code>repeated .Car car = 9;</code>
     */
    public java.util.List<PersonProtos.Car> getCarList() {
      return car_;
    }
    /**
     * <code>repeated .Car car = 9;</code>
     */
    public java.util.List<? extends PersonProtos.CarOrBuilder> 
        getCarOrBuilderList() {
      return car_;
    }
    /**
     * <code>repeated .Car car = 9;</code>
     */
    public int getCarCount() {
      return car_.size();
    }
    /**
     * <code>repeated .Car car = 9;</code>
     */
    public PersonProtos.Car getCar(int index) {
      return car_.get(index);
    }
    /**
     * <code>repeated .Car car = 9;</code>
     */
    public PersonProtos.CarOrBuilder getCarOrBuilder(
        int index) {
      return car_.get(index);
    }

    private void initFields() {
      id_ = 0;
      name_ = "";
      email_ = "";
      money_ = 0;
      hair_ = PersonProtos.Hair.getDefaultInstance();
      someBytes_ = com.google.protobuf.ByteString.EMPTY;
      language_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      someNumber_ = java.util.Collections.emptyList();
      car_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasHair()) {
        if (!getHair().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getCarCount(); i++) {
        if (!getCar(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getEmailBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, money_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, hair_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, someBytes_);
      }
      for (int i = 0; i < language_.size(); i++) {
        output.writeBytes(7, language_.getByteString(i));
      }
      for (int i = 0; i < someNumber_.size(); i++) {
        output.writeInt32(8, someNumber_.get(i));
      }
      for (int i = 0; i < car_.size(); i++) {
        output.writeMessage(9, car_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEmailBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, money_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, hair_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, someBytes_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < language_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(language_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getLanguageList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < someNumber_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(someNumber_.get(i));
        }
        size += dataSize;
        size += 1 * getSomeNumberList().size();
      }
      for (int i = 0; i < car_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, car_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static PersonProtos.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PersonProtos.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PersonProtos.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PersonProtos.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PersonProtos.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PersonProtos.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static PersonProtos.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static PersonProtos.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static PersonProtos.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PersonProtos.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PersonProtos.Person prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements PersonProtos.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PersonProtos.internal_static_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PersonProtos.internal_static_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PersonProtos.Person.class, PersonProtos.Person.Builder.class);
      }

      // Construct using PersonProtos.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHairFieldBuilder();
          getCarFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        money_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (hairBuilder_ == null) {
          hair_ = PersonProtos.Hair.getDefaultInstance();
        } else {
          hairBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        someBytes_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        language_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        someNumber_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        if (carBuilder_ == null) {
          car_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          carBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PersonProtos.internal_static_Person_descriptor;
      }

      public PersonProtos.Person getDefaultInstanceForType() {
        return PersonProtos.Person.getDefaultInstance();
      }

      public PersonProtos.Person build() {
        PersonProtos.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PersonProtos.Person buildPartial() {
        PersonProtos.Person result = new PersonProtos.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.email_ = email_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.money_ = money_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (hairBuilder_ == null) {
          result.hair_ = hair_;
        } else {
          result.hair_ = hairBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.someBytes_ = someBytes_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          language_ = new com.google.protobuf.UnmodifiableLazyStringList(
              language_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.language_ = language_;
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          someNumber_ = java.util.Collections.unmodifiableList(someNumber_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.someNumber_ = someNumber_;
        if (carBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100)) {
            car_ = java.util.Collections.unmodifiableList(car_);
            bitField0_ = (bitField0_ & ~0x00000100);
          }
          result.car_ = car_;
        } else {
          result.car_ = carBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PersonProtos.Person) {
          return mergeFrom((PersonProtos.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PersonProtos.Person other) {
        if (other == PersonProtos.Person.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000004;
          email_ = other.email_;
          onChanged();
        }
        if (other.hasMoney()) {
          setMoney(other.getMoney());
        }
        if (other.hasHair()) {
          mergeHair(other.getHair());
        }
        if (other.hasSomeBytes()) {
          setSomeBytes(other.getSomeBytes());
        }
        if (!other.language_.isEmpty()) {
          if (language_.isEmpty()) {
            language_ = other.language_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureLanguageIsMutable();
            language_.addAll(other.language_);
          }
          onChanged();
        }
        if (!other.someNumber_.isEmpty()) {
          if (someNumber_.isEmpty()) {
            someNumber_ = other.someNumber_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureSomeNumberIsMutable();
            someNumber_.addAll(other.someNumber_);
          }
          onChanged();
        }
        if (carBuilder_ == null) {
          if (!other.car_.isEmpty()) {
            if (car_.isEmpty()) {
              car_ = other.car_;
              bitField0_ = (bitField0_ & ~0x00000100);
            } else {
              ensureCarIsMutable();
              car_.addAll(other.car_);
            }
            onChanged();
          }
        } else {
          if (!other.car_.isEmpty()) {
            if (carBuilder_.isEmpty()) {
              carBuilder_.dispose();
              carBuilder_ = null;
              car_ = other.car_;
              bitField0_ = (bitField0_ & ~0x00000100);
              carBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCarFieldBuilder() : null;
            } else {
              carBuilder_.addAllMessages(other.car_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (hasHair()) {
          if (!getHair().isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getCarCount(); i++) {
          if (!getCar(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PersonProtos.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PersonProtos.Person) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // required string name = 2;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // optional string email = 3;
      private java.lang.Object email_ = "";
      /**
       * <code>optional string email = 3;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }

      // optional int32 money = 4;
      private int money_ ;
      /**
       * <code>optional int32 money = 4;</code>
       */
      public boolean hasMoney() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 money = 4;</code>
       */
      public int getMoney() {
        return money_;
      }
      /**
       * <code>optional int32 money = 4;</code>
       */
      public Builder setMoney(int value) {
        bitField0_ |= 0x00000008;
        money_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 money = 4;</code>
       */
      public Builder clearMoney() {
        bitField0_ = (bitField0_ & ~0x00000008);
        money_ = 0;
        onChanged();
        return this;
      }

      // optional .Hair hair = 5;
      private PersonProtos.Hair hair_ = PersonProtos.Hair.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          PersonProtos.Hair, PersonProtos.Hair.Builder, PersonProtos.HairOrBuilder> hairBuilder_;
      /**
       * <code>optional .Hair hair = 5;</code>
       */
      public boolean hasHair() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .Hair hair = 5;</code>
       */
      public PersonProtos.Hair getHair() {
        if (hairBuilder_ == null) {
          return hair_;
        } else {
          return hairBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Hair hair = 5;</code>
       */
      public Builder setHair(PersonProtos.Hair value) {
        if (hairBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          hair_ = value;
          onChanged();
        } else {
          hairBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .Hair hair = 5;</code>
       */
      public Builder setHair(
          PersonProtos.Hair.Builder builderForValue) {
        if (hairBuilder_ == null) {
          hair_ = builderForValue.build();
          onChanged();
        } else {
          hairBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .Hair hair = 5;</code>
       */
      public Builder mergeHair(PersonProtos.Hair value) {
        if (hairBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              hair_ != PersonProtos.Hair.getDefaultInstance()) {
            hair_ =
              PersonProtos.Hair.newBuilder(hair_).mergeFrom(value).buildPartial();
          } else {
            hair_ = value;
          }
          onChanged();
        } else {
          hairBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .Hair hair = 5;</code>
       */
      public Builder clearHair() {
        if (hairBuilder_ == null) {
          hair_ = PersonProtos.Hair.getDefaultInstance();
          onChanged();
        } else {
          hairBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .Hair hair = 5;</code>
       */
      public PersonProtos.Hair.Builder getHairBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getHairFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Hair hair = 5;</code>
       */
      public PersonProtos.HairOrBuilder getHairOrBuilder() {
        if (hairBuilder_ != null) {
          return hairBuilder_.getMessageOrBuilder();
        } else {
          return hair_;
        }
      }
      /**
       * <code>optional .Hair hair = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          PersonProtos.Hair, PersonProtos.Hair.Builder, PersonProtos.HairOrBuilder> 
          getHairFieldBuilder() {
        if (hairBuilder_ == null) {
          hairBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              PersonProtos.Hair, PersonProtos.Hair.Builder, PersonProtos.HairOrBuilder>(
                  hair_,
                  getParentForChildren(),
                  isClean());
          hair_ = null;
        }
        return hairBuilder_;
      }

      // optional bytes someBytes = 6;
      private com.google.protobuf.ByteString someBytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes someBytes = 6;</code>
       */
      public boolean hasSomeBytes() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bytes someBytes = 6;</code>
       */
      public com.google.protobuf.ByteString getSomeBytes() {
        return someBytes_;
      }
      /**
       * <code>optional bytes someBytes = 6;</code>
       */
      public Builder setSomeBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        someBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes someBytes = 6;</code>
       */
      public Builder clearSomeBytes() {
        bitField0_ = (bitField0_ & ~0x00000020);
        someBytes_ = getDefaultInstance().getSomeBytes();
        onChanged();
        return this;
      }

      // repeated string language = 7;
      private com.google.protobuf.LazyStringList language_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureLanguageIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          language_ = new com.google.protobuf.LazyStringArrayList(language_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated string language = 7;</code>
       */
      public java.util.List<java.lang.String>
          getLanguageList() {
        return java.util.Collections.unmodifiableList(language_);
      }
      /**
       * <code>repeated string language = 7;</code>
       */
      public int getLanguageCount() {
        return language_.size();
      }
      /**
       * <code>repeated string language = 7;</code>
       */
      public java.lang.String getLanguage(int index) {
        return language_.get(index);
      }
      /**
       * <code>repeated string language = 7;</code>
       */
      public com.google.protobuf.ByteString
          getLanguageBytes(int index) {
        return language_.getByteString(index);
      }
      /**
       * <code>repeated string language = 7;</code>
       */
      public Builder setLanguage(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLanguageIsMutable();
        language_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string language = 7;</code>
       */
      public Builder addLanguage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLanguageIsMutable();
        language_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string language = 7;</code>
       */
      public Builder addAllLanguage(
          java.lang.Iterable<java.lang.String> values) {
        ensureLanguageIsMutable();
        super.addAll(values, language_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string language = 7;</code>
       */
      public Builder clearLanguage() {
        language_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string language = 7;</code>
       */
      public Builder addLanguageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLanguageIsMutable();
        language_.add(value);
        onChanged();
        return this;
      }

      // repeated int32 someNumber = 8;
      private java.util.List<java.lang.Integer> someNumber_ = java.util.Collections.emptyList();
      private void ensureSomeNumberIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          someNumber_ = new java.util.ArrayList<java.lang.Integer>(someNumber_);
          bitField0_ |= 0x00000080;
         }
      }
      /**
       * <code>repeated int32 someNumber = 8;</code>
       */
      public java.util.List<java.lang.Integer>
          getSomeNumberList() {
        return java.util.Collections.unmodifiableList(someNumber_);
      }
      /**
       * <code>repeated int32 someNumber = 8;</code>
       */
      public int getSomeNumberCount() {
        return someNumber_.size();
      }
      /**
       * <code>repeated int32 someNumber = 8;</code>
       */
      public int getSomeNumber(int index) {
        return someNumber_.get(index);
      }
      /**
       * <code>repeated int32 someNumber = 8;</code>
       */
      public Builder setSomeNumber(
          int index, int value) {
        ensureSomeNumberIsMutable();
        someNumber_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 someNumber = 8;</code>
       */
      public Builder addSomeNumber(int value) {
        ensureSomeNumberIsMutable();
        someNumber_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 someNumber = 8;</code>
       */
      public Builder addAllSomeNumber(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureSomeNumberIsMutable();
        super.addAll(values, someNumber_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 someNumber = 8;</code>
       */
      public Builder clearSomeNumber() {
        someNumber_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }

      // repeated .Car car = 9;
      private java.util.List<PersonProtos.Car> car_ =
        java.util.Collections.emptyList();
      private void ensureCarIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          car_ = new java.util.ArrayList<PersonProtos.Car>(car_);
          bitField0_ |= 0x00000100;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          PersonProtos.Car, PersonProtos.Car.Builder, PersonProtos.CarOrBuilder> carBuilder_;

      /**
       * <code>repeated .Car car = 9;</code>
       */
      public java.util.List<PersonProtos.Car> getCarList() {
        if (carBuilder_ == null) {
          return java.util.Collections.unmodifiableList(car_);
        } else {
          return carBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Car car = 9;</code>
       */
      public int getCarCount() {
        if (carBuilder_ == null) {
          return car_.size();
        } else {
          return carBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Car car = 9;</code>
       */
      public PersonProtos.Car getCar(int index) {
        if (carBuilder_ == null) {
          return car_.get(index);
        } else {
          return carBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Car car = 9;</code>
       */
      public Builder setCar(
          int index, PersonProtos.Car value) {
        if (carBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCarIsMutable();
          car_.set(index, value);
          onChanged();
        } else {
          carBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Car car = 9;</code>
       */
      public Builder setCar(
          int index, PersonProtos.Car.Builder builderForValue) {
        if (carBuilder_ == null) {
          ensureCarIsMutable();
          car_.set(index, builderForValue.build());
          onChanged();
        } else {
          carBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Car car = 9;</code>
       */
      public Builder addCar(PersonProtos.Car value) {
        if (carBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCarIsMutable();
          car_.add(value);
          onChanged();
        } else {
          carBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Car car = 9;</code>
       */
      public Builder addCar(
          int index, PersonProtos.Car value) {
        if (carBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCarIsMutable();
          car_.add(index, value);
          onChanged();
        } else {
          carBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Car car = 9;</code>
       */
      public Builder addCar(
          PersonProtos.Car.Builder builderForValue) {
        if (carBuilder_ == null) {
          ensureCarIsMutable();
          car_.add(builderForValue.build());
          onChanged();
        } else {
          carBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Car car = 9;</code>
       */
      public Builder addCar(
          int index, PersonProtos.Car.Builder builderForValue) {
        if (carBuilder_ == null) {
          ensureCarIsMutable();
          car_.add(index, builderForValue.build());
          onChanged();
        } else {
          carBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Car car = 9;</code>
       */
      public Builder addAllCar(
          java.lang.Iterable<? extends PersonProtos.Car> values) {
        if (carBuilder_ == null) {
          ensureCarIsMutable();
          super.addAll(values, car_);
          onChanged();
        } else {
          carBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Car car = 9;</code>
       */
      public Builder clearCar() {
        if (carBuilder_ == null) {
          car_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
          onChanged();
        } else {
          carBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Car car = 9;</code>
       */
      public Builder removeCar(int index) {
        if (carBuilder_ == null) {
          ensureCarIsMutable();
          car_.remove(index);
          onChanged();
        } else {
          carBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Car car = 9;</code>
       */
      public PersonProtos.Car.Builder getCarBuilder(
          int index) {
        return getCarFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Car car = 9;</code>
       */
      public PersonProtos.CarOrBuilder getCarOrBuilder(
          int index) {
        if (carBuilder_ == null) {
          return car_.get(index);  } else {
          return carBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Car car = 9;</code>
       */
      public java.util.List<? extends PersonProtos.CarOrBuilder> 
           getCarOrBuilderList() {
        if (carBuilder_ != null) {
          return carBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(car_);
        }
      }
      /**
       * <code>repeated .Car car = 9;</code>
       */
      public PersonProtos.Car.Builder addCarBuilder() {
        return getCarFieldBuilder().addBuilder(
            PersonProtos.Car.getDefaultInstance());
      }
      /**
       * <code>repeated .Car car = 9;</code>
       */
      public PersonProtos.Car.Builder addCarBuilder(
          int index) {
        return getCarFieldBuilder().addBuilder(
            index, PersonProtos.Car.getDefaultInstance());
      }
      /**
       * <code>repeated .Car car = 9;</code>
       */
      public java.util.List<PersonProtos.Car.Builder> 
           getCarBuilderList() {
        return getCarFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          PersonProtos.Car, PersonProtos.Car.Builder, PersonProtos.CarOrBuilder> 
          getCarFieldBuilder() {
        if (carBuilder_ == null) {
          carBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              PersonProtos.Car, PersonProtos.Car.Builder, PersonProtos.CarOrBuilder>(
                  car_,
                  ((bitField0_ & 0x00000100) == 0x00000100),
                  getParentForChildren(),
                  isClean());
          car_ = null;
        }
        return carBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Person)
    }

    static {
      defaultInstance = new Person(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Person)
  }

  public interface HairOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string color = 1;
    /**
     * <code>required string color = 1;</code>
     */
    boolean hasColor();
    /**
     * <code>required string color = 1;</code>
     */
    java.lang.String getColor();
    /**
     * <code>required string color = 1;</code>
     */
    com.google.protobuf.ByteString
        getColorBytes();

    // required int32 length = 2;
    /**
     * <code>required int32 length = 2;</code>
     */
    boolean hasLength();
    /**
     * <code>required int32 length = 2;</code>
     */
    int getLength();
  }
  /**
   * Protobuf type {@code Hair}
   */
  public static final class Hair extends
      com.google.protobuf.GeneratedMessage
      implements HairOrBuilder {
    // Use Hair.newBuilder() to construct.
    private Hair(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Hair(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Hair defaultInstance;
    public static Hair getDefaultInstance() {
      return defaultInstance;
    }

    public Hair getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Hair(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              color_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              length_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PersonProtos.internal_static_Hair_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PersonProtos.internal_static_Hair_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PersonProtos.Hair.class, PersonProtos.Hair.Builder.class);
    }

    public static com.google.protobuf.Parser<Hair> PARSER =
        new com.google.protobuf.AbstractParser<Hair>() {
      public Hair parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Hair(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Hair> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string color = 1;
    public static final int COLOR_FIELD_NUMBER = 1;
    private java.lang.Object color_;
    /**
     * <code>required string color = 1;</code>
     */
    public boolean hasColor() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string color = 1;</code>
     */
    public java.lang.String getColor() {
      java.lang.Object ref = color_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          color_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string color = 1;</code>
     */
    public com.google.protobuf.ByteString
        getColorBytes() {
      java.lang.Object ref = color_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        color_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 length = 2;
    public static final int LENGTH_FIELD_NUMBER = 2;
    private int length_;
    /**
     * <code>required int32 length = 2;</code>
     */
    public boolean hasLength() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 length = 2;</code>
     */
    public int getLength() {
      return length_;
    }

    private void initFields() {
      color_ = "";
      length_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasColor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getColorBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, length_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getColorBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, length_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static PersonProtos.Hair parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PersonProtos.Hair parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PersonProtos.Hair parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PersonProtos.Hair parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PersonProtos.Hair parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PersonProtos.Hair parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static PersonProtos.Hair parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static PersonProtos.Hair parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static PersonProtos.Hair parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PersonProtos.Hair parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PersonProtos.Hair prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Hair}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements PersonProtos.HairOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PersonProtos.internal_static_Hair_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PersonProtos.internal_static_Hair_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PersonProtos.Hair.class, PersonProtos.Hair.Builder.class);
      }

      // Construct using PersonProtos.Hair.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        color_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        length_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PersonProtos.internal_static_Hair_descriptor;
      }

      public PersonProtos.Hair getDefaultInstanceForType() {
        return PersonProtos.Hair.getDefaultInstance();
      }

      public PersonProtos.Hair build() {
        PersonProtos.Hair result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PersonProtos.Hair buildPartial() {
        PersonProtos.Hair result = new PersonProtos.Hair(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.color_ = color_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.length_ = length_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PersonProtos.Hair) {
          return mergeFrom((PersonProtos.Hair)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PersonProtos.Hair other) {
        if (other == PersonProtos.Hair.getDefaultInstance()) return this;
        if (other.hasColor()) {
          bitField0_ |= 0x00000001;
          color_ = other.color_;
          onChanged();
        }
        if (other.hasLength()) {
          setLength(other.getLength());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasColor()) {
          
          return false;
        }
        if (!hasLength()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PersonProtos.Hair parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PersonProtos.Hair) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string color = 1;
      private java.lang.Object color_ = "";
      /**
       * <code>required string color = 1;</code>
       */
      public boolean hasColor() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string color = 1;</code>
       */
      public java.lang.String getColor() {
        java.lang.Object ref = color_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          color_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string color = 1;</code>
       */
      public com.google.protobuf.ByteString
          getColorBytes() {
        java.lang.Object ref = color_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          color_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string color = 1;</code>
       */
      public Builder setColor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        color_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string color = 1;</code>
       */
      public Builder clearColor() {
        bitField0_ = (bitField0_ & ~0x00000001);
        color_ = getDefaultInstance().getColor();
        onChanged();
        return this;
      }
      /**
       * <code>required string color = 1;</code>
       */
      public Builder setColorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        color_ = value;
        onChanged();
        return this;
      }

      // required int32 length = 2;
      private int length_ ;
      /**
       * <code>required int32 length = 2;</code>
       */
      public boolean hasLength() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 length = 2;</code>
       */
      public int getLength() {
        return length_;
      }
      /**
       * <code>required int32 length = 2;</code>
       */
      public Builder setLength(int value) {
        bitField0_ |= 0x00000002;
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 length = 2;</code>
       */
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000002);
        length_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Hair)
    }

    static {
      defaultInstance = new Hair(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Hair)
  }

  public interface CarOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string color = 1;
    /**
     * <code>required string color = 1;</code>
     */
    boolean hasColor();
    /**
     * <code>required string color = 1;</code>
     */
    java.lang.String getColor();
    /**
     * <code>required string color = 1;</code>
     */
    com.google.protobuf.ByteString
        getColorBytes();

    // required string manufacturer = 2;
    /**
     * <code>required string manufacturer = 2;</code>
     */
    boolean hasManufacturer();
    /**
     * <code>required string manufacturer = 2;</code>
     */
    java.lang.String getManufacturer();
    /**
     * <code>required string manufacturer = 2;</code>
     */
    com.google.protobuf.ByteString
        getManufacturerBytes();
  }
  /**
   * Protobuf type {@code Car}
   */
  public static final class Car extends
      com.google.protobuf.GeneratedMessage
      implements CarOrBuilder {
    // Use Car.newBuilder() to construct.
    private Car(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Car(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Car defaultInstance;
    public static Car getDefaultInstance() {
      return defaultInstance;
    }

    public Car getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Car(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              color_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              manufacturer_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PersonProtos.internal_static_Car_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PersonProtos.internal_static_Car_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PersonProtos.Car.class, PersonProtos.Car.Builder.class);
    }

    public static com.google.protobuf.Parser<Car> PARSER =
        new com.google.protobuf.AbstractParser<Car>() {
      public Car parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Car(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Car> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string color = 1;
    public static final int COLOR_FIELD_NUMBER = 1;
    private java.lang.Object color_;
    /**
     * <code>required string color = 1;</code>
     */
    public boolean hasColor() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string color = 1;</code>
     */
    public java.lang.String getColor() {
      java.lang.Object ref = color_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          color_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string color = 1;</code>
     */
    public com.google.protobuf.ByteString
        getColorBytes() {
      java.lang.Object ref = color_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        color_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string manufacturer = 2;
    public static final int MANUFACTURER_FIELD_NUMBER = 2;
    private java.lang.Object manufacturer_;
    /**
     * <code>required string manufacturer = 2;</code>
     */
    public boolean hasManufacturer() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string manufacturer = 2;</code>
     */
    public java.lang.String getManufacturer() {
      java.lang.Object ref = manufacturer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          manufacturer_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string manufacturer = 2;</code>
     */
    public com.google.protobuf.ByteString
        getManufacturerBytes() {
      java.lang.Object ref = manufacturer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        manufacturer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      color_ = "";
      manufacturer_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasColor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasManufacturer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getColorBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getManufacturerBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getColorBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getManufacturerBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static PersonProtos.Car parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PersonProtos.Car parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PersonProtos.Car parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PersonProtos.Car parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PersonProtos.Car parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PersonProtos.Car parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static PersonProtos.Car parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static PersonProtos.Car parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static PersonProtos.Car parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PersonProtos.Car parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PersonProtos.Car prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Car}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements PersonProtos.CarOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PersonProtos.internal_static_Car_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PersonProtos.internal_static_Car_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PersonProtos.Car.class, PersonProtos.Car.Builder.class);
      }

      // Construct using PersonProtos.Car.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        color_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        manufacturer_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PersonProtos.internal_static_Car_descriptor;
      }

      public PersonProtos.Car getDefaultInstanceForType() {
        return PersonProtos.Car.getDefaultInstance();
      }

      public PersonProtos.Car build() {
        PersonProtos.Car result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PersonProtos.Car buildPartial() {
        PersonProtos.Car result = new PersonProtos.Car(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.color_ = color_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.manufacturer_ = manufacturer_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PersonProtos.Car) {
          return mergeFrom((PersonProtos.Car)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PersonProtos.Car other) {
        if (other == PersonProtos.Car.getDefaultInstance()) return this;
        if (other.hasColor()) {
          bitField0_ |= 0x00000001;
          color_ = other.color_;
          onChanged();
        }
        if (other.hasManufacturer()) {
          bitField0_ |= 0x00000002;
          manufacturer_ = other.manufacturer_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasColor()) {
          
          return false;
        }
        if (!hasManufacturer()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PersonProtos.Car parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PersonProtos.Car) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string color = 1;
      private java.lang.Object color_ = "";
      /**
       * <code>required string color = 1;</code>
       */
      public boolean hasColor() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string color = 1;</code>
       */
      public java.lang.String getColor() {
        java.lang.Object ref = color_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          color_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string color = 1;</code>
       */
      public com.google.protobuf.ByteString
          getColorBytes() {
        java.lang.Object ref = color_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          color_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string color = 1;</code>
       */
      public Builder setColor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        color_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string color = 1;</code>
       */
      public Builder clearColor() {
        bitField0_ = (bitField0_ & ~0x00000001);
        color_ = getDefaultInstance().getColor();
        onChanged();
        return this;
      }
      /**
       * <code>required string color = 1;</code>
       */
      public Builder setColorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        color_ = value;
        onChanged();
        return this;
      }

      // required string manufacturer = 2;
      private java.lang.Object manufacturer_ = "";
      /**
       * <code>required string manufacturer = 2;</code>
       */
      public boolean hasManufacturer() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string manufacturer = 2;</code>
       */
      public java.lang.String getManufacturer() {
        java.lang.Object ref = manufacturer_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          manufacturer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string manufacturer = 2;</code>
       */
      public com.google.protobuf.ByteString
          getManufacturerBytes() {
        java.lang.Object ref = manufacturer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          manufacturer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string manufacturer = 2;</code>
       */
      public Builder setManufacturer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        manufacturer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string manufacturer = 2;</code>
       */
      public Builder clearManufacturer() {
        bitField0_ = (bitField0_ & ~0x00000002);
        manufacturer_ = getDefaultInstance().getManufacturer();
        onChanged();
        return this;
      }
      /**
       * <code>required string manufacturer = 2;</code>
       */
      public Builder setManufacturerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        manufacturer_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Car)
    }

    static {
      defaultInstance = new Car(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Car)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Person_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Hair_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Hair_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Car_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Car_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014person.proto\"\241\001\n\006Person\022\n\n\002id\030\001 \002(\005\022\014\n" +
      "\004name\030\002 \002(\t\022\r\n\005email\030\003 \001(\t\022\r\n\005money\030\004 \001(" +
      "\005\022\023\n\004hair\030\005 \001(\0132\005.Hair\022\021\n\tsomeBytes\030\006 \001(" +
      "\014\022\020\n\010language\030\007 \003(\t\022\022\n\nsomeNumber\030\010 \003(\005\022" +
      "\021\n\003car\030\t \003(\0132\004.Car\"%\n\004Hair\022\r\n\005color\030\001 \002(" +
      "\t\022\016\n\006length\030\002 \002(\005\"*\n\003Car\022\r\n\005color\030\001 \002(\t\022" +
      "\024\n\014manufacturer\030\002 \002(\tB\016B\014PersonProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Person_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Person_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Person_descriptor,
              new java.lang.String[] { "Id", "Name", "Email", "Money", "Hair", "SomeBytes", "Language", "SomeNumber", "Car", });
          internal_static_Hair_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Hair_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Hair_descriptor,
              new java.lang.String[] { "Color", "Length", });
          internal_static_Car_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Car_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Car_descriptor,
              new java.lang.String[] { "Color", "Manufacturer", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
